//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_de_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialClinico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HistorialClinico()
        {
            this.Tratamiento = new HashSet<Tratamiento>();
        }
    
        public int IdHistoriaClinica { get; set; }
        public int CitaId { get; set; }
        public int HistorialGeneralId { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string Observaciones { get; set; }
        public int IdTipoTratamiento { get; set; }
    
        public virtual Cita Cita { get; set; }
        public virtual HistorialGeneral HistorialGeneral { get; set; }
        public virtual TipoTratamiento TipoTratamiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tratamiento> Tratamiento { get; set; }
    }
}
