//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_de_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tratamiento
    {
        public int IdTratamiento { get; set; }
        public int CitaId { get; set; }
        public int TipoId { get; set; }
        public string Estado { get; set; }
        public System.DateTime FechaProximaCita { get; set; }
        public System.TimeSpan HoraProximaCita { get; set; }
        public System.DateTime InicioTratamiento { get; set; }
        public System.DateTime FinTratamiento { get; set; }
        public int IdHistorialClinico { get; set; }
        public string Diagnostico { get; set; }
    
        public virtual Cita Cita { get; set; }
        public virtual HistorialClinico HistorialClinico { get; set; }
        public virtual TipoTratamiento TipoTratamiento { get; set; }
    }
}
